#!/bin/bash

# For use on WSL.
# JLinkGDBServerCL is a symbolic link to the Windows installation of JLinkGDBServerCL.exe
# Reason is because only Windows executables have access to the device's COM ports.

JLinkGDBServerCL -device nrf52832_xxaa -if swd -port 1338 -nolocalhostonly
