#ifndef DONGLE_TELEMETRY__H
#define DONGLE_TELEMETRY__H

#define TELEM_TYPE_RESTART 0x00
#define TELEM_TYPE_SCAN_RESULT 0x01
#define TELEM_TYPE_BROADCAST_ID_MISMATCH 0x02
#define TELEM_TYPE_BROADCAST_TRACK_NEW 0x03
#define TELEM_TYPE_BROADCAST_TRACK_MATCH 0x04
#define TELEM_TYPE_ENCOUNTER 0x05

#endif