/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_manufacturer_name_string       16
#define gattdb_system_id                      18
#define gattdb_ota_control                    21
#define gattdb_throughput_indications         24
#define gattdb_throughput_notifications       28
#define gattdb_transmission_on                32
#define gattdb_throughput_result              36
#define gattdb_connection_phy                 41
#define gattdb_connection_interval            45
#define gattdb_responder_latency              49
#define gattdb_supervision_timeout            53
#define gattdb_pdu_size                       57
#define gattdb_mtu_size                       61


#endif // __GATT_DB_H
